#!/bin/bash
#
# Raspberry Pi 3 misc setup and cleanup
#

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

export TARGET_FW=${TARGET_ROOT}/boot/firmware

# 'ib_iser' is not a module and cannot be loaded
rm -f ${TARGET_ROOT}/lib/modules-load.d/open-iscsi.conf

