#!/bin/bash
#
# Builds the kernel for Raspberry Pi 3
#

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

mkdir -p ${CDIB_RPI3_BASE_DIR}

(cd ${CDIB_RPI3_BASE_DIR}
 if [ ! -d linux ]; then
     git clone --depth=1 https://github.com/raspberrypi/linux
 else
     echo "Using already existant kernel directory"
 fi
)

export CROSS_COMPILE=aarch64-linux-gnu-
export ARCH=arm64

(cd ${CDIB_RPI3_BASE_DIR}/linux
 make bcmrpi3_defconfig
 make -j 4 Image dtbs modules
)

