#!/bin/bash
#
# Installs the kernel for Raspberry Pi 3
#

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

mkdir -p ${CDIB_RPI3_BASE_DIR}

(cd ${CDIB_RPI3_BASE_DIR}
 if [ ! -d init4boot ]; then
     git clone --depth=1 https://github.com/florath/init4boot.git
 else
     echo "Using already existant init4boot directory"
 fi
)
