- local_loop:
    name: image0
    size: 768MiB

- partitioning:
    base: image0
    label: mbr
    partitions:
      - name: boot
        flags: [ boot, primary ]
        type: 0e
        size: 64MiB
        mkfs:
          type: vfat
          mount:
            mount_point: /boot/firmware
            fstab:
              options: defaults
              dump-freq: 0
              fsck-passno: 2
      - name: root
        flags: [ primary ]
        size: 100%
        mkfs:
          type: ext4
          mount:
            mount_point: /
            fstab:
              options: defaults
              dump-freq: 0
              fsck-passno: 1
